<?php

use Illuminate\Database\Seeder;

class MghDtvariantTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('mgh_dtvariant')->delete();
        
        \DB::table('mgh_dtvariant')->insert(array (
            0 => 
            array (
                'idvariant' => 0,
                'variant_kode' => 'variant_kode',
                'variant_nama' => 'variant_nama',
                'variant_harga' => 0.0,
                'variant_stock' => 0.0,
                'variant_date' => 'variant_da',
                'variant_author' => 'variant_',
                'variant_ls_stock' => 0.0,
                'variant_ls_date' => 'variant_ls',
                'variant_ls_author' => 'variant_',
            ),
            1 => 
            array (
                'idvariant' => 39,
                'variant_kode' => 'ALR',
                'variant_nama' => 'ALLURE WOMAN',
                'variant_harga' => 2000.0,
                'variant_stock' => 205.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 87759.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            2 => 
            array (
                'idvariant' => 41,
                'variant_kode' => 'ATM',
                'variant_nama' => 'ANGEL T MUGLER',
                'variant_harga' => 2000.0,
                'variant_stock' => 180.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 27977.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            3 => 
            array (
                'idvariant' => 42,
                'variant_kode' => 'AVE',
                'variant_nama' => '5TH AVENUE E ARDEN',
                'variant_harga' => 2500.0,
                'variant_stock' => 192.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 85731.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            4 => 
            array (
                'idvariant' => 44,
                'variant_kode' => 'BDS',
                'variant_nama' => 'BE DELICIOUS DKNY W',
                'variant_harga' => 2500.0,
                'variant_stock' => 150.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 23468.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            5 => 
            array (
                'idvariant' => 45,
                'variant_kode' => 'BFM',
                'variant_nama' => 'BVLGARI FEMME W',
                'variant_harga' => 2000.0,
                'variant_stock' => 82.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 29464.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            6 => 
            array (
                'idvariant' => 46,
                'variant_kode' => 'BLW',
                'variant_nama' => 'BVLGARI BLUE WOMAN',
                'variant_harga' => 2000.0,
                'variant_stock' => 292.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 25642.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            7 => 
            array (
                'idvariant' => 47,
                'variant_kode' => 'CDN',
                'variant_nama' => 'BELONG CELINE DION W',
                'variant_harga' => 2000.0,
                'variant_stock' => 300.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 30937.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            8 => 
            array (
                'idvariant' => 48,
                'variant_kode' => 'CHH',
                'variant_nama' => 'HAPPY HEART W',
                'variant_harga' => 2000.0,
                'variant_stock' => 132.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 28644.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            9 => 
            array (
                'idvariant' => 49,
                'variant_kode' => 'CRS',
                'variant_nama' => 'CURIOUS BRITNEY W',
                'variant_harga' => 2000.0,
                'variant_stock' => 182.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 23576.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            10 => 
            array (
                'idvariant' => 50,
                'variant_kode' => 'CWW',
                'variant_nama' => 'COOL WATER W',
                'variant_harga' => 2000.0,
                'variant_stock' => 163.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 79425.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            11 => 
            array (
                'idvariant' => 52,
                'variant_kode' => 'DNW',
                'variant_nama' => 'DUNE WOMAN',
                'variant_harga' => 2000.0,
                'variant_stock' => 90.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 28370.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            12 => 
            array (
                'idvariant' => 53,
                'variant_kode' => 'ECW',
                'variant_nama' => 'ESCAPE WOMAN',
                'variant_harga' => 2000.0,
                'variant_stock' => 185.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 29445.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            13 => 
            array (
                'idvariant' => 54,
                'variant_kode' => 'EDC',
                'variant_nama' => 'EAU DE CARTIER W',
                'variant_harga' => 2000.0,
                'variant_stock' => 130.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 30937.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            14 => 
            array (
                'idvariant' => 55,
                'variant_kode' => 'ENV',
                'variant_nama' => 'GUCCI ENVE ME W',
                'variant_harga' => 2000.0,
                'variant_stock' => 227.5,
                'variant_date' => '2007-03-28',
                'variant_author' => 'admin',
                'variant_ls_stock' => 0.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            15 => 
            array (
                'idvariant' => 56,
                'variant_kode' => 'ETW',
                'variant_nama' => 'ETERNITY WOMAN',
                'variant_harga' => 2000.0,
                'variant_stock' => 135.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 60390.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            16 => 
            array (
                'idvariant' => 57,
                'variant_kode' => 'EXO',
                'variant_nama' => 'PLEASURE EXOTIC W',
                'variant_harga' => 2000.0,
                'variant_stock' => 115.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 76342.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            17 => 
            array (
                'idvariant' => 59,
                'variant_kode' => 'GT',
                'variant_nama' => 'GREEN TEA ARDEN W',
                'variant_harga' => 2000.0,
                'variant_stock' => 82.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 60181.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            18 => 
            array (
                'idvariant' => 61,
                'variant_kode' => 'BDR',
                'variant_nama' => 'BOSS DEEP RED W',
                'variant_harga' => 2000.0,
                'variant_stock' => 219.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 21018.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            19 => 
            array (
                'idvariant' => 62,
                'variant_kode' => 'ICM',
                'variant_nama' => 'ICANTO CHARM SF W',
                'variant_harga' => 2000.0,
                'variant_stock' => 232.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 54831.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            20 => 
            array (
                'idvariant' => 63,
                'variant_kode' => 'ISW',
                'variant_nama' => 'ISSEYMIYAKE W',
                'variant_harga' => 2000.0,
                'variant_stock' => 255.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 57014.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            21 => 
            array (
                'idvariant' => 64,
                'variant_kode' => 'KIS',
                'variant_nama' => 'ISLAND KISS ESC W',
                'variant_harga' => 2000.0,
                'variant_stock' => 200.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 55131.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            22 => 
            array (
                'idvariant' => 65,
                'variant_kode' => 'KD',
                'variant_nama' => 'KENZO DAUN W',
                'variant_harga' => 2000.0,
                'variant_stock' => 140.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 82301.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            23 => 
            array (
                'idvariant' => 66,
                'variant_kode' => 'KF',
                'variant_nama' => 'KENZO FLOWER',
                'variant_harga' => 2000.0,
                'variant_stock' => 220.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 10989.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            24 => 
            array (
                'idvariant' => 67,
                'variant_kode' => 'KLW',
                'variant_nama' => 'KENZO LEUPAR W',
                'variant_harga' => 2000.0,
                'variant_stock' => 170.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 31294.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            25 => 
            array (
                'idvariant' => 69,
                'variant_kode' => 'LVE',
                'variant_nama' => 'LIVE J-LO W',
                'variant_harga' => 2000.0,
                'variant_stock' => 92.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 220.0,
                'variant_ls_date' => '2007-05-10',
                'variant_ls_author' => 'OLLA',
            ),
            26 => 
            array (
                'idvariant' => 70,
                'variant_kode' => 'MGL',
                'variant_nama' => 'MIAMI GLOW J-LO W',
                'variant_harga' => 2500.0,
                'variant_stock' => 200.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 30976.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            27 => 
            array (
                'idvariant' => 71,
                'variant_kode' => 'OMN',
                'variant_nama' => 'OMNIA BVLGARI W',
                'variant_harga' => 2000.0,
                'variant_stock' => 152.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 89102.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            28 => 
            array (
                'idvariant' => 72,
                'variant_kode' => 'PHW',
                'variant_nama' => 'PARIS HILTON W',
                'variant_harga' => 2500.0,
                'variant_stock' => 247.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 33984.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            29 => 
            array (
                'idvariant' => 73,
                'variant_kode' => 'PLS',
                'variant_nama' => 'PLEASURE ESTEE W',
                'variant_harga' => 2000.0,
                'variant_stock' => 155.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 79641.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            30 => 
            array (
                'idvariant' => 74,
                'variant_kode' => 'PRJ',
                'variant_nama' => 'PREMIER JOURE NINA W',
                'variant_harga' => 2500.0,
                'variant_stock' => 142.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 60595.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            31 => 
            array (
                'idvariant' => 75,
                'variant_kode' => 'PRP',
                'variant_nama' => 'PURE PURPLE HUGO W',
                'variant_harga' => 2000.0,
                'variant_stock' => 240.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 4615.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            32 => 
            array (
                'idvariant' => 77,
                'variant_kode' => 'SD',
                'variant_nama' => 'SUI DREAM ANNA SUI W',
                'variant_harga' => 2000.0,
                'variant_stock' => 235.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 73135.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            33 => 
            array (
                'idvariant' => 78,
                'variant_kode' => 'SGT',
                'variant_nama' => 'SEXY GARFITTI ESC W',
                'variant_harga' => 2000.0,
                'variant_stock' => 34.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 38864.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            34 => 
            array (
                'idvariant' => 79,
                'variant_kode' => 'SMS',
                'variant_nama' => 'SAMSARA GUARLAIN W',
                'variant_harga' => 3000.0,
                'variant_stock' => 159.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 20916.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            35 => 
            array (
                'idvariant' => 81,
                'variant_kode' => 'STL',
                'variant_nama' => 'STILL J-LO W',
                'variant_harga' => 2000.0,
                'variant_stock' => 265.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 14898.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            36 => 
            array (
                'idvariant' => 82,
                'variant_kode' => 'SXY',
                'variant_nama' => '212 SEXY CAROLINA W',
                'variant_harga' => 2000.0,
                'variant_stock' => 145.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 75872.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            37 => 
            array (
                'idvariant' => 84,
                'variant_kode' => 'TRB',
                'variant_nama' => 'TRIBU BENNETON W',
                'variant_harga' => 2000.0,
                'variant_stock' => 220.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 30087.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            38 => 
            array (
                'idvariant' => 85,
                'variant_kode' => 'TRS',
                'variant_nama' => 'TRESOR LANCOME W',
                'variant_harga' => 2000.0,
                'variant_stock' => 250.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 59735.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            39 => 
            array (
                'idvariant' => 86,
                'variant_kode' => 'TRU',
                'variant_nama' => 'TRUE LOVE ARDEN W',
                'variant_harga' => 2000.0,
                'variant_stock' => 280.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 27162.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            40 => 
            array (
                'idvariant' => 87,
                'variant_kode' => 'VNL',
                'variant_nama' => 'VANILLA BODYSHOP W',
                'variant_harga' => 2000.0,
                'variant_stock' => 260.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 30920.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            41 => 
            array (
                'idvariant' => 88,
                'variant_kode' => 'WMW',
                'variant_nama' => 'WHITE MUSK BODYSHOP',
                'variant_harga' => 3000.0,
                'variant_stock' => 254.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 75989.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            42 => 
            array (
                'idvariant' => 89,
                'variant_kode' => '222W',
                'variant_nama' => '212 WOMAN HERERRA',
                'variant_harga' => 2000.0,
                'variant_stock' => 188.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 90.68000000000000682121026329696178436279296875,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            43 => 
            array (
                'idvariant' => 90,
                'variant_kode' => 'BLA',
                'variant_nama' => 'BVLGARI ACVA U',
                'variant_harga' => 2000.0,
                'variant_stock' => 277.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 9925.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            44 => 
            array (
                'idvariant' => 91,
                'variant_kode' => 'SA',
                'variant_nama' => 'SWISS ARMY U',
                'variant_harga' => 2000.0,
                'variant_stock' => 155.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 26196.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            45 => 
            array (
                'idvariant' => 93,
                'variant_kode' => 'CKS',
                'variant_nama' => 'CK SUMMER U',
                'variant_harga' => 2000.0,
                'variant_stock' => 95.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 29864.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            46 => 
            array (
                'idvariant' => 94,
                'variant_kode' => 'CKB',
                'variant_nama' => 'CK Be',
                'variant_harga' => 2000.0,
                'variant_stock' => 179.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 29428.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            47 => 
            array (
                'idvariant' => 95,
                'variant_kode' => 'LB',
                'variant_nama' => 'LIGHT BLUE D&G',
                'variant_harga' => 2500.0,
                'variant_stock' => 230.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 29160.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            48 => 
            array (
                'idvariant' => 96,
                'variant_kode' => 'LMN',
                'variant_nama' => 'LEMON',
                'variant_harga' => 2000.0,
                'variant_stock' => 102.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 80.0,
                'variant_ls_date' => '2007-05-10',
                'variant_ls_author' => 'OLLA',
            ),
            49 => 
            array (
                'idvariant' => 97,
                'variant_kode' => 'SGS',
                'variant_nama' => 'SUGUS CANDY',
                'variant_harga' => 2000.0,
                'variant_stock' => 97.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 19487.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            50 => 
            array (
                'idvariant' => 99,
                'variant_kode' => 'APL',
                'variant_nama' => 'APPLE GREEN',
                'variant_harga' => 2000.0,
                'variant_stock' => 35.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 9478.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            51 => 
            array (
                'idvariant' => 100,
                'variant_kode' => 'MRK',
                'variant_nama' => 'PASSION FRUITS',
                'variant_harga' => 2000.0,
                'variant_stock' => 25.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 10970.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            52 => 
            array (
                'idvariant' => 101,
                'variant_kode' => 'JSM',
                'variant_nama' => 'JASMIN',
                'variant_harga' => 2000.0,
                'variant_stock' => 37.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 25339.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            53 => 
            array (
                'idvariant' => 102,
                'variant_kode' => 'LUX',
                'variant_nama' => 'LUX SOAP',
                'variant_harga' => 2000.0,
                'variant_stock' => 47.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 28014.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            54 => 
            array (
                'idvariant' => 103,
                'variant_kode' => 'MLN',
                'variant_nama' => 'MELON',
                'variant_harga' => 2000.0,
                'variant_stock' => 100.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 11000.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            55 => 
            array (
                'idvariant' => 104,
                'variant_kode' => 'ORG',
                'variant_nama' => 'ORANGE',
                'variant_harga' => 2000.0,
                'variant_stock' => 95.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 11000.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            56 => 
            array (
                'idvariant' => 106,
                'variant_kode' => 'CDL',
                'variant_nama' => 'CUDDLE TALC',
                'variant_harga' => 2000.0,
                'variant_stock' => 70.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 10985.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            57 => 
            array (
                'idvariant' => 107,
                'variant_kode' => 'CSN',
                'variant_nama' => 'CUSSON',
                'variant_harga' => 2000.0,
                'variant_stock' => 82.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 90210.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            58 => 
            array (
                'idvariant' => 108,
                'variant_kode' => 'AMB',
                'variant_nama' => 'AMBIPHUR AQUA',
                'variant_harga' => 2000.0,
                'variant_stock' => 52.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 90960.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            59 => 
            array (
                'idvariant' => 110,
                'variant_kode' => 'ALS',
                'variant_nama' => 'ALLURE SPORT M ',
                'variant_harga' => 2000.0,
                'variant_stock' => 155.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 49131.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            60 => 
            array (
                'idvariant' => 111,
                'variant_kode' => 'AQL',
                'variant_nama' => 'AQUAELEMENT HUGO M',
                'variant_harga' => 2000.0,
                'variant_stock' => 146.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 10499.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            61 => 
            array (
                'idvariant' => 113,
                'variant_kode' => 'BBC',
                'variant_nama' => 'BVLGARI BLACK M',
                'variant_harga' => 2500.0,
                'variant_stock' => 223.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 399.8500000000000227373675443232059478759765625,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            62 => 
            array (
                'idvariant' => 114,
                'variant_kode' => 'BDS-M',
                'variant_nama' => 'BE DELICIOUS MAN',
                'variant_harga' => 2000.0,
                'variant_stock' => 155.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 30955.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            63 => 
            array (
                'idvariant' => 115,
                'variant_kode' => 'BJV',
                'variant_nama' => 'BLUE JEAN VERSACE M',
                'variant_harga' => 2000.0,
                'variant_stock' => 68.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 56045.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            64 => 
            array (
                'idvariant' => 116,
                'variant_kode' => 'BLE',
                'variant_nama' => 'BLUE EMOTION M',
                'variant_harga' => 2500.0,
                'variant_stock' => 194.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 27757.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            65 => 
            array (
                'idvariant' => 117,
                'variant_kode' => 'BLM',
                'variant_nama' => 'BVLGARI BLUE MAN',
                'variant_harga' => 2000.0,
                'variant_stock' => 224.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 88817.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            66 => 
            array (
                'idvariant' => 118,
                'variant_kode' => 'BSM',
                'variant_nama' => 'BENNETON SPORT MAN',
                'variant_harga' => 2000.0,
                'variant_stock' => 132.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 48387.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            67 => 
            array (
                'idvariant' => 119,
                'variant_kode' => 'BSC',
                'variant_nama' => 'SELECTION BOSS M',
                'variant_harga' => 2500.0,
                'variant_stock' => 222.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 23652.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            68 => 
            array (
                'idvariant' => 122,
                'variant_kode' => 'BRT',
                'variant_nama' => 'BURRBERRY BRIT M',
                'variant_harga' => 2000.0,
                'variant_stock' => 216.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 30235.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            69 => 
            array (
                'idvariant' => 123,
                'variant_kode' => 'BXS',
                'variant_nama' => 'BLACK XS PACCO M',
                'variant_harga' => 2000.0,
                'variant_stock' => 232.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 86437.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            70 => 
            array (
                'idvariant' => 124,
                'variant_kode' => 'CDM',
                'variant_nama' => 'CLEAR DAY EA M',
                'variant_harga' => 2000.0,
                'variant_stock' => 300.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 30317.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            71 => 
            array (
                'idvariant' => 125,
                'variant_kode' => 'CHM',
                'variant_nama' => 'CLINIQUE HAPPY M',
                'variant_harga' => 2000.0,
                'variant_stock' => 246.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 395.3999999999999772626324556767940521240234375,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            72 => 
            array (
                'idvariant' => 126,
                'variant_kode' => 'CRV',
                'variant_nama' => 'CRAVE CK M',
                'variant_harga' => 2000.0,
                'variant_stock' => 174.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 28930.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            73 => 
            array (
                'idvariant' => 127,
                'variant_kode' => 'CUK',
                'variant_nama' => 'FCUK M',
                'variant_harga' => 2000.0,
                'variant_stock' => 285.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 50066.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            74 => 
            array (
                'idvariant' => 128,
                'variant_kode' => 'CWM',
                'variant_nama' => 'COOL WATER M',
                'variant_harga' => 2000.0,
                'variant_stock' => 78.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 80080.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            75 => 
            array (
                'idvariant' => 131,
                'variant_kode' => 'DDR',
                'variant_nama' => 'DUNHILL D RED M',
                'variant_harga' => 2000.0,
                'variant_stock' => 235.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 55888.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            76 => 
            array (
                'idvariant' => 132,
                'variant_kode' => 'DRC',
                'variant_nama' => 'DERRICK M',
                'variant_harga' => 2000.0,
                'variant_stock' => 300.0,
                'variant_date' => '2007-05-09',
                'variant_author' => 'admin',
                'variant_ls_stock' => 30807.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            77 => 
            array (
                'idvariant' => 133,
                'variant_kode' => 'DKK',
                'variant_nama' => 'DRAKKAR NOIR M',
                'variant_harga' => 2000.0,
                'variant_stock' => 227.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 52356.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            78 => 
            array (
                'idvariant' => 134,
                'variant_kode' => 'DRK',
                'variant_nama' => 'DARK BLUE HUGO M',
                'variant_harga' => 2500.0,
                'variant_stock' => 88.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 84861.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            79 => 
            array (
                'idvariant' => 135,
                'variant_kode' => 'ECH',
                'variant_nama' => 'ECHO DAVIDOFF M',
                'variant_harga' => 2000.0,
                'variant_stock' => 105.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 25781.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            80 => 
            array (
                'idvariant' => 136,
                'variant_kode' => 'ECM',
                'variant_nama' => 'ESCAPE M',
                'variant_harga' => 2000.0,
                'variant_stock' => 196.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 350.0,
                'variant_ls_date' => '2007-05-10',
                'variant_ls_author' => 'OLLA',
            ),
            81 => 
            array (
                'idvariant' => 137,
                'variant_kode' => 'EGS',
                'variant_nama' => 'ENERGISE BOSS M',
                'variant_harga' => 2000.0,
                'variant_stock' => 160.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 40893.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            82 => 
            array (
                'idvariant' => 139,
                'variant_kode' => 'ETM',
                'variant_nama' => 'ETERNITY M',
                'variant_harga' => 2000.0,
                'variant_stock' => 292.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 73630.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            83 => 
            array (
                'idvariant' => 140,
                'variant_kode' => 'EXT',
                'variant_nama' => 'EXTREME BVLGARI M',
                'variant_harga' => 2000.0,
                'variant_stock' => 203.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 292.5,
                'variant_ls_date' => '2007-05-09',
                'variant_ls_author' => 'admin',
            ),
            84 => 
            array (
                'idvariant' => 141,
                'variant_kode' => 'FHR',
                'variant_nama' => 'FAHREINHEIT CD M',
                'variant_harga' => 2000.0,
                'variant_stock' => 92.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 27386.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            85 => 
            array (
                'idvariant' => 142,
                'variant_kode' => 'FRB',
                'variant_nama' => 'FERRARI BLACK M',
                'variant_harga' => 2000.0,
                'variant_stock' => 160.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 58605.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            86 => 
            array (
                'idvariant' => 143,
                'variant_kode' => 'INM',
                'variant_nama' => 'INMOTION BOSS M',
                'variant_harga' => 2000.0,
                'variant_stock' => 230.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 55228.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            87 => 
            array (
                'idvariant' => 144,
                'variant_kode' => 'JSS',
                'variant_nama' => 'JAZZ YSL M',
                'variant_harga' => 2000.0,
                'variant_stock' => 149.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 29824.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            88 => 
            array (
                'idvariant' => 145,
                'variant_kode' => 'JGB',
                'variant_nama' => 'JAGUAR BLUE M',
                'variant_harga' => 2500.0,
                'variant_stock' => 300.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 51669.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            89 => 
            array (
                'idvariant' => 147,
                'variant_kode' => 'KB',
                'variant_nama' => 'KENZO BATANG M',
                'variant_harga' => 2000.0,
                'variant_stock' => 121.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 220.0,
                'variant_ls_date' => '2007-05-10',
                'variant_ls_author' => 'OLLA',
            ),
            90 => 
            array (
                'idvariant' => 148,
                'variant_kode' => 'NTE',
                'variant_nama' => 'NOTTE BVLGARI M',
                'variant_harga' => 2000.0,
                'variant_stock' => 160.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 78736.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            91 => 
            array (
                'idvariant' => 150,
                'variant_kode' => 'PSM',
                'variant_nama' => 'POLO SPORT M',
                'variant_harga' => 2000.0,
                'variant_stock' => 119.5,
                'variant_date' => '2007-05-09',
                'variant_author' => 'admin',
                'variant_ls_stock' => 77435.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            92 => 
            array (
                'idvariant' => 152,
                'variant_kode' => 'SNT',
                'variant_nama' => 'SENTIMENT ESC M',
                'variant_harga' => 2000.0,
                'variant_stock' => 123.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 35650.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            93 => 
            array (
                'idvariant' => 153,
                'variant_kode' => 'SOL',
                'variant_nama' => 'SOUL HUGO BOSS M',
                'variant_harga' => 2500.0,
                'variant_stock' => 260.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 51010.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            94 => 
            array (
                'idvariant' => 154,
                'variant_kode' => 'X3',
                'variant_nama' => 'XXX ETIENNE AIGNER M',
                'variant_harga' => 3000.0,
                'variant_stock' => 139.19999999999998863131622783839702606201171875,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 56996.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            95 => 
            array (
                'idvariant' => 155,
                'variant_kode' => '222',
                'variant_nama' => '212 MAN',
                'variant_harga' => 3000.0,
                'variant_stock' => 5.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 38682.9000000000014551915228366851806640625,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            96 => 
            array (
                'idvariant' => 156,
                'variant_kode' => 'SLM',
                'variant_nama' => 'SHALIMAR GUARLAIN M',
                'variant_harga' => 3000.0,
                'variant_stock' => 75.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 20948.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            97 => 
            array (
                'idvariant' => 158,
                'variant_kode' => 'ACD',
                'variant_nama' => 'ARMANI CODE W',
                'variant_harga' => 2000.0,
                'variant_stock' => 145.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 255.0,
                'variant_ls_date' => '2007-03-31',
                'variant_ls_author' => 'admin',
            ),
            98 => 
            array (
                'idvariant' => 160,
                'variant_kode' => 'BLD',
                'variant_nama' => 'BVLGARI LADY',
                'variant_harga' => 2000.0,
                'variant_stock' => 152.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 177.5,
                'variant_ls_date' => '2007-03-31',
                'variant_ls_author' => 'admin',
            ),
            99 => 
            array (
                'idvariant' => 161,
                'variant_kode' => 'BPS',
                'variant_nama' => 'BEYOND PARADISE',
                'variant_harga' => 2000.0,
                'variant_stock' => 155.0,
                'variant_date' => '2007-03-31',
                'variant_author' => 'admin',
                'variant_ls_stock' => 0.0,
                'variant_ls_date' => '2007-03-31',
                'variant_ls_author' => 'admin',
            ),
            100 => 
            array (
                'idvariant' => 162,
                'variant_kode' => 'MGT',
                'variant_nama' => 'MAGNETISEM ESC W',
                'variant_harga' => 2000.0,
                'variant_stock' => 192.5,
                'variant_date' => '2007-03-31',
                'variant_author' => 'admin',
                'variant_ls_stock' => 0.0,
                'variant_ls_date' => '2007-03-31',
                'variant_ls_author' => 'admin',
            ),
            101 => 
            array (
                'idvariant' => 163,
                'variant_kode' => 'ADW',
                'variant_nama' => 'AQUA DI GIO W',
                'variant_harga' => 2000.0,
                'variant_stock' => 60.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 170.0,
                'variant_ls_date' => '2007-03-31',
                'variant_ls_author' => 'admin',
            ),
            102 => 
            array (
                'idvariant' => 164,
                'variant_kode' => 'DDB',
                'variant_nama' => 'DUNHILL DESIRE BLUE',
                'variant_harga' => 2000.0,
                'variant_stock' => 111.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 273.0,
                'variant_ls_date' => '2007-05-09',
                'variant_ls_author' => 'admin',
            ),
            103 => 
            array (
                'idvariant' => 43,
                'variant_kode' => 'BBL',
                'variant_nama' => 'BURBERRY OF LONDON W',
                'variant_harga' => 2500.0,
                'variant_stock' => 278.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 11752.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            104 => 
            array (
                'idvariant' => 51,
                'variant_kode' => 'C5',
                'variant_nama' => 'CHANEL 5 W',
                'variant_harga' => 2000.0,
                'variant_stock' => 200.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 29052.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            105 => 
            array (
                'idvariant' => 58,
                'variant_kode' => 'FTY',
                'variant_nama' => 'FANTASY BRITNEY W',
                'variant_harga' => 2000.0,
                'variant_stock' => 156.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 60449.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            106 => 
            array (
                'idvariant' => 68,
                'variant_kode' => 'LIP',
                'variant_nama' => 'LOVE IN PARIS NINA W',
                'variant_harga' => 2000.0,
                'variant_stock' => 185.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 60701.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            107 => 
            array (
                'idvariant' => 76,
                'variant_kode' => 'RSH',
                'variant_nama' => 'RUSH GUCCI W',
                'variant_harga' => 2000.0,
                'variant_stock' => 95.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 30949.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            108 => 
            array (
                'idvariant' => 92,
                'variant_kode' => 'CK',
                'variant_nama' => 'CK ONE U',
                'variant_harga' => 2000.0,
                'variant_stock' => 150.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 55345.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            109 => 
            array (
                'idvariant' => 98,
                'variant_kode' => 'GUM',
                'variant_nama' => 'BUBBLE GUM',
                'variant_harga' => 2000.0,
                'variant_stock' => 46.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 89872.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            110 => 
            array (
                'idvariant' => 105,
                'variant_kode' => 'STW',
                'variant_nama' => 'STRAWBERRY',
                'variant_harga' => 2000.0,
                'variant_stock' => 55.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 29985.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            111 => 
            array (
                'idvariant' => 112,
                'variant_kode' => 'ARM',
                'variant_nama' => 'ARMY MAN HUGO',
                'variant_harga' => 2500.0,
                'variant_stock' => 280.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 82361.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            112 => 
            array (
                'idvariant' => 120,
                'variant_kode' => 'BST',
                'variant_nama' => 'BEST CEVIGNON M',
                'variant_harga' => 2000.0,
                'variant_stock' => 210.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 25627.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            113 => 
            array (
                'idvariant' => 121,
                'variant_kode' => 'BTL',
                'variant_nama' => 'BOTTLE BOSS M',
                'variant_harga' => 2000.0,
                'variant_stock' => 187.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 49707.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            114 => 
            array (
                'idvariant' => 129,
                'variant_kode' => 'DCL',
                'variant_nama' => 'CECLARATION CARTIER ',
                'variant_harga' => 3000.0,
                'variant_stock' => 166.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 29155.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            115 => 
            array (
                'idvariant' => 138,
                'variant_kode' => 'EST',
                'variant_nama' => 'ESSENTIAL LCT M',
                'variant_harga' => 2000.0,
                'variant_stock' => 210.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 25911.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            116 => 
            array (
                'idvariant' => 146,
                'variant_kode' => 'KLM',
                'variant_nama' => 'KENZO LEUPAR M',
                'variant_harga' => 2000.0,
                'variant_stock' => 75.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 39866.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            117 => 
            array (
                'idvariant' => 151,
                'variant_kode' => 'RUG',
                'variant_nama' => 'ROUGE LACOSTE M',
                'variant_harga' => 2000.0,
                'variant_stock' => 165.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 30862.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            118 => 
            array (
                'idvariant' => 159,
                'variant_kode' => 'RIR',
                'variant_nama' => 'ROCK IN RIO ESC W',
                'variant_harga' => 2000.0,
                'variant_stock' => 200.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 199.5,
                'variant_ls_date' => '2007-03-31',
                'variant_ls_author' => 'admin',
            ),
            119 => 
            array (
                'idvariant' => 40,
                'variant_kode' => 'ARW',
                'variant_nama' => 'ARMY WOMAN HUGO',
                'variant_harga' => 2500.0,
                'variant_stock' => 273.80000000000001136868377216160297393798828125,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 87798.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            120 => 
            array (
                'idvariant' => 60,
                'variant_kode' => 'GLW',
                'variant_nama' => 'GLOW J-LO W',
                'variant_harga' => 2000.0,
                'variant_stock' => 242.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 27585.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            121 => 
            array (
                'idvariant' => 80,
                'variant_kode' => 'SNW',
                'variant_nama' => 'SENTIMENT ESC W',
                'variant_harga' => 2000.0,
                'variant_stock' => 137.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 59084.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            122 => 
            array (
                'idvariant' => 83,
                'variant_kode' => 'TOP',
                'variant_nama' => 'TOUCH OF PINK LCT W',
                'variant_harga' => 2000.0,
                'variant_stock' => 195.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 59148.5,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            123 => 
            array (
                'idvariant' => 109,
                'variant_kode' => 'ADM',
                'variant_nama' => 'ACQUA DI GIO M',
                'variant_harga' => 2000.0,
                'variant_stock' => 234.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 43210.0999999999985448084771633148193359375,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            124 => 
            array (
                'idvariant' => 149,
                'variant_kode' => 'PGM',
                'variant_nama' => 'POLO GREEN M',
                'variant_harga' => 2000.0,
                'variant_stock' => 112.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 30916.0,
                'variant_ls_date' => '2007-03-28',
                'variant_ls_author' => 'admin',
            ),
            125 => 
            array (
                'idvariant' => 165,
                'variant_kode' => 'CWG',
                'variant_nama' => 'COOLWATER GAME W',
                'variant_harga' => 2000.0,
                'variant_stock' => 250.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 300.0,
                'variant_ls_date' => '2007-05-02',
                'variant_ls_author' => 'admin',
            ),
            126 => 
            array (
                'idvariant' => 166,
                'variant_kode' => 'ETS',
                'variant_nama' => 'ETERNITY SUMMER W',
                'variant_harga' => 2000.0,
                'variant_stock' => 170.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 300.0,
                'variant_ls_date' => '2007-05-02',
                'variant_ls_author' => 'admin',
            ),
            127 => 
            array (
                'idvariant' => 167,
                'variant_kode' => 'EPH',
                'variant_nama' => 'EUPHORIA CK W',
                'variant_harga' => 2000.0,
                'variant_stock' => 192.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 283.5,
                'variant_ls_date' => '2007-05-02',
                'variant_ls_author' => 'admin',
            ),
            128 => 
            array (
                'idvariant' => 168,
                'variant_kode' => 'CRL',
                'variant_nama' => 'CHARLY ',
                'variant_harga' => 2000.0,
                'variant_stock' => 217.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 300.0,
                'variant_ls_date' => '2007-05-02',
                'variant_ls_author' => 'admin',
            ),
            129 => 
            array (
                'idvariant' => 169,
                'variant_kode' => 'LVD',
                'variant_nama' => 'LAVENDER',
                'variant_harga' => 2000.0,
                'variant_stock' => 280.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 300.0,
                'variant_ls_date' => '2007-05-02',
                'variant_ls_author' => 'admin',
            ),
            130 => 
            array (
                'idvariant' => 170,
                'variant_kode' => 'PBL',
                'variant_nama' => 'POLO BLACK M',
                'variant_harga' => 2000.0,
                'variant_stock' => 134.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 285.0,
                'variant_ls_date' => '2007-05-02',
                'variant_ls_author' => 'admin',
            ),
            131 => 
            array (
                'idvariant' => 171,
                'variant_kode' => 'DVB',
                'variant_nama' => 'DAVID BACKHAM M',
                'variant_harga' => 2000.0,
                'variant_stock' => 121.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 300.0,
                'variant_ls_date' => '2007-05-10',
                'variant_ls_author' => 'OLLA',
            ),
            132 => 
            array (
                'idvariant' => 172,
                'variant_kode' => 'LBQ',
                'variant_nama' => 'LOVING BOUQUET ESC',
                'variant_harga' => 2000.0,
                'variant_stock' => 250.0,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 292.5,
                'variant_ls_date' => '2007-05-02',
                'variant_ls_author' => 'admin',
            ),
            133 => 
            array (
                'idvariant' => 173,
                'variant_kode' => 'LVL',
                'variant_nama' => 'LOVELY SARAH J PRKR',
                'variant_harga' => 2000.0,
                'variant_stock' => 146.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 0.0,
                'variant_ls_date' => '2007-05-10',
                'variant_ls_author' => 'OLLA',
            ),
            134 => 
            array (
                'idvariant' => 174,
                'variant_kode' => 'PHM',
                'variant_nama' => 'PARIS HILTON MAN',
                'variant_harga' => 2000.0,
                'variant_stock' => 267.5,
                'variant_date' => '2007-05-10',
                'variant_author' => 'OLLA',
                'variant_ls_stock' => 0.0,
                'variant_ls_date' => '2007-05-10',
                'variant_ls_author' => 'OLLA',
            ),
        ));
        
        
    }
}
